### ISSUE TITLE
Find a way to use Github pages with a custom SSL domain

### ISSUE THREAD

**Issue by tilmx** [meetalva/website#29]

**Comment by marionebl** [comment]
now.sh could be an option, too: https://stacked-website-fifvgqqjdf.now.sh

---

* https://zeit.co/blog/now-alias
* https://zeit.co/blog/now-alias#instant-free-ssl

**Comment by tilmx** [comment]
Sounds interesting!

**Comment by leonardodino** [comment]
if i may suggest: [netlify](https://www.netlify.com/) all the way!
- free 
- can handle forms 
- 100% static and CDN out-of-the-box 
- builds your website on git push (any shell command, like compiling the less file)
- the above works on any branch (the team can preview changes before merging)

(not affiliated, it's just really amazing)

## update:
well, guess it's already implemented in #43 😂

**Comment by tilmx** [comment]
@marionebl should we try this out instead of zeit.co?

**Comment by marionebl** [comment]
Sure, let's give netlify a shot.

**Comment by tilmx** [comment]
@leonardodino we didn’t get the zeit.co alias running, so let’s try netlify. Thanks for the recommendation! 🚀

**Comment by MaxShalom** [comment]
If Netlify doesn't work, another option is [surge.sh](http://surge.sh). Not sure if it suits your needs but, it can deploy static websites just by typing `surge` into the command line. It also gives you unlimited subdomains with SSL at .surge.sh and it's free. 

Also, not affiliated, just really like it.

**Comment by leonardodino** [comment]
@tilmx If you need any help, just `@` me!

It's pretty straightforward anyways, login with `GitHub` and <u>link</u> this repo with it.
Additionally I let it manage the `DNS`, it allows better CDN routing on the bare/root domain.

**PS**: I advise against the [`deploy`](https://github.com/meetalva/website/blob/90c61bf/package.json#L19), script  for full CI experience.
There's an easy but old [tutorial](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) that's still valid. Easier than the docs (:

---

`surge.sh` is super nice also, i used it a lot before discovering netlify... but the integrated CI in netlify means you won't need travis and mangling with deploy credentials.
if it fails a build it will notify here on the repo, the same way as travis.

**Comment by tilmx** [comment]
Netlify seems to be really nice, thanks for your recommendation!
I tried it, but was running into huge problems with the SSL certificates (refused it because of "bad DNS"). Will try it later again.

**Comment by tilmx** [comment]
Works fine with Netlify now! Thank you very much for suggesting the services and supporting, @leonardodino & @MaxShalom! 🚀
